#ifndef PAW3399_H
#define PAW3399_H

#define REG_PRODUCT_ID			0x00
#define REG_REVISION_ID			0x01
#define REG_MOTION				0x02
#define REG_DELTA_X_L			0x03
#define REG_DELTA_X_H			0x04
#define REG_DELTA_Y_L			0x05
#define REG_DELTA_Y_H			0x06
#define REG_SQUAL				0x07
#define REG_RAWDATA_SUM			0x08
#define REG_MAXIMUM_RAWDATA		0x09
#define REG_MINIMUM_RAWDATA		0x0A
#define REG_SHUTTER_LOWER		0x0B
#define REG_SHUTTER_UPPER		0x0C
#define REG_OBSERVATION			0x15
#define REG_MOTION_BURST		0x16
#define REG_POWER_UP_RESET		0x3A
#define REG_SHUTDOWN			0x3B
#define REG_PERFORMANCE			0x40
#define REG_SET_RESOLUTION		0x47
#define REG_RESOLUTION_X_LOW	0x48
#define REG_RESOLUTION_X_HIGH	0x49
#define REG_RESOLUTION_Y_LOW	0x4A
#define REG_RESOLUTION_Y_HIGH	0x4B
#define REG_ANGLE_SNAP			0x56
#define REG_RAWDATA_OUTPUT		0x58
#define REG_RAWDATA_STATUS		0x59
#define REG_RIPPLE_CONTROL		0x5A
#define REG_AXIS_CONTROL		0x5B
#define REG_MOTION_CTRL			0x5C
#define REG_INV_PRODUCT_ID		0x5F
#define REG_RUN_DOWNSHIFT		0x77
#define REG_REST1_RATE			0x78
#define REG_REST1_DOWNSHIFT		0x79
#define REG_REST2_RATE			0x7A
#define REG_REST2_DOWNSHIFT		0x7B
#define REG_REST3_RATE			0x7C
#define REG_RUN_DOWNSHIFT_MULT	0x7D
#define REG_REST_DOWNSHIFT_MULT	0x7E
#define REG_BANK_SELECT			0x7F

void paw3399_init(void);

#endif